version: "3.4"

services:
  frontend:
    container_name: citizen-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    # depends_on:
    #   - backend
    # networks:
    #   - geo-lpo
    ports:
      - "${PORT-4200}:${PORT-4200}"
