version: "3.4"

services:
  frontend:
    container_name: citizen-front
    image: gnc-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - citizen-kane

  backend:
    container_name: citizen-back
    image: gnc-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./VERSION:/VERSION
      - ./config:/config
      - ./external_modules:/external_modules
      - ./media:/media
    depends_on:
      - db
    networks:
      - citizen-kane

  db:
    container_name: citizen-db
    image: postgis/postgis:10-2.5-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${DB_NAME-geocitizen}
      - POSTGRES_USER=${DB_USER-geonatuser}
      - POSTGRES_PASSWORD=${DB_PASSWORD-monpassachanger}
    volumes:
      - citizen_data:/var/lib/postgresql/data/pgdata
    networks:
      - citizen-kane

  nginx:
    container_name: citizen-nginx
    image: gnc-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
    ports:
      - "${NGINX_PORT-80}:80"
    volumes:
      - ./config/backoffice_htpasswd:/etc/nginx/conf/.htpasswd
    networks:
      - citizen-kane

networks:
  citizen-kane:
    external: false
volumes:
  citizen_data:
